### ISSUE TITLE
音声の追加

### ISSUE THREAD

**Issue by tapoh22334** [tapoh22334/hatodokei#7]
## VOICEVOX 系 OK

VOICEVOX:四国めたん
VOICEVOX:ずんだもん
VOICEVOX:春日部つむぎ
VOICEVOX:雨晴はう
VOICEVOX:波音リツ
VOICEVOX:玄野武宏
VOICEVOX:白上虎太郎
VOICEVOX:冥鳴ひまり
VOICEVOX:九州そら
VOICEVOX:剣崎雌雄
VOICEVOX:WhiteCUL
VOICEVOX:ちび式じい
VOICEVOX:櫻歌ミコ
VOICEVOX:小夜/SAYO
VOICEVOX:ナースロボ＿タイプＴ
VOICEVOX:†聖騎士 紅桜†
VOICEVOX:雀松朱司
VOICEVOX:麒ヶ島宗麟
VOICEVOX:春歌ナナ
VOICEVOX:猫使アル
VOICEVOX:猫使ビィ

## VOICEVOX系 制限あり

VOICEVOX:青山龍星　企業利用に制限あり
VOICEVOX:後鬼　企業利用に制限あり

## NG

VOICEVOX:もち子(cv 明日葉よもぎ)　音声作品・音声素材・ゲーム作品を除いて商用・非商用で利用可能
VOICEVOX:No.7　非商用で利用可能で

**Comment by iwase22334** [comment]
## COEIROINK 系

COEIROINK:つくよみちゃん
COEIROINK:MANA
COEIROINK:KANA
COEIROINK:おふとんP
COEIROINK:AI声優-朱花
COEIROINK:AI声優-青葉
COEIROINK:AI声優-銀芽

## OEIROINK 系 制限あり

COEIROINK:ディアちゃん
COEIROINK:アルマちゃん

**Comment by iwase22334** [comment]
## LMROID系 制限あり

全体

**Comment by iwase22334** [comment]
ITVOICE, SHAREVOX 要調査。今回はパス。
